### PR TITLE
Feature/3 query data

### LINKED ISSUE #3: Query dummy data
Write an action that queries dummy data and saves it to the Redux store.

### PR DESCRIPTION
**Pull request by drewbo**
Close #3 

Pulls data from a local store on map load and map move. Only writes additions to the local store and `Draw.store`. Future improvements:
- [x] track which tiles we've fetched data for and don't query
- interrupt pending requests when a new one is issued (maybe? cc: @kamicut )

Update: only storing features in the `Draw.store` (no need to duplicate in a local Redux store)

### CODE REVIEW

**Comment by kamicut** [comment]
@drewbo interrupt requests is interesting

**Comment by kamicut** [comment]
We can also throttle the request action as the user is panning around the map.

**Comment by drewbo** [comment]
@kamicut Still need to add debounce and could also reduce network requests by not requesting tiles which are fulling contained within already requested tiles (it doesn't add any data)

**Comment by dereklieu** [comment]
Works with the new changes. 👍

**Pull request merged**
