### PR TITLE
Line continuation ui

### PR DESCRIPTION
**Pull request by drewbo**
Connects line continuation to the UI

### CODE REVIEW

**Comment by drewbo** [comment]
thanks @felskia @dereklieu; I'll add the active class; the correct undo functionality will come with https://github.com/mapbox/mapbox-gl-draw/pull/615

**Comment by felskia** [comment]
@drewbo ok, did some styling and might take another look at it in ticket #37. Otherwise, there is still one tool that doesn't have an active class which is the first, adding a line.

**Comment by dereklieu** [comment]
👍 changes LGTM, happy to ticket out the delete and active class for adding lines separately.

**Comment by drewbo** [comment]
@dereklieu should have the active class now; the undo can be ticketed out

**Pull request merged**
